---
- name: Build and push Docker image
  hosts: all
  become: yes
  tasks:
  - name: Build the Docker image
    shell: docker build . -t angular/pfe
    
  - name: Tag the image
    shell: docker tag angular/pfe beffa/project_pfe-2022:releaseV1
  
  - name: Push the image to Docker Hub
    shell: docker push beffa/project_pfe-2022:releaseV1
