---
- name: Build and push Docker images
  hosts: all
  become: yes
  
  tasks:
 
  - name: Copy directory from Ansible server to remote host
    copy:
      src: /var/lib/awx/projects/_53__cicd_pfe_project/
      dest: /tmp/angular-project/
  
  
  - name: Build the Docker image
    shell: cd /tmp/angular-project/ && docker build . -t angular/pfe
    
  - name: Run Container
    shell: docker run angular/pfe 
    
  - name: Tag the image
    shell: docker tag angular/pfe beffa/project_pfe-2022:releaseV1
  
  - name: Push the image to Docker Hub
    shell: docker push beffa/project_pfe-2022:releaseV1
    
  #Stop and remove all container
  - name: remove local coantiner
    shell: docker rm $(docker ps -a -q)
  #remove all local images
  - name: remove local images
    shell: docker rmi -f $(docker images -aq)  
    
  - name: Delete Directory
    file:
      path: /tmp/angular-project/
      state: absent
