---
- name: Build and push Docker images
  hosts: all
  become: yes
  
  tasks:
 
  - name: Copy directory from Ansible server to remote host
    copy:
      src: /var/lib/awx/projects/_53__cicd_pfe_project
      dest: /tmp/angular-project
      remote_src: yes
      
  - name: Build the Docker image
    docker_image:
      path: /tmp/_53__cicd_pfe_project/Dockerfile
      name: angular/pfe
      state: build    
      
  - name: Tag the image
    shell: docker tag angular/pfe beffa/project_pfe-2022:releaseV1
  
  - name: Push the image to Docker Hub
    shell: docker push beffa/project_pfe-2022:releaseV1
