---
- name: Build and push Docker images
  hosts: all
  become: yes
  
  tasks:
 
  - name: Copy directory from Ansible server to remote host
    copy:
      src: /var/lib/awx/projects/_53__cicd_pfe_project/
      dest: /tmp/angular-project/
  
  - name: check whoami
    shell: whoami
    register: whoami_output
  - name: debug
    debug:
      var: whoami_output
    
  - name: shell command
    shell: chown -R root:root /tmp/angular-project && chmod 777 -R /tmp/angular-project
  - name: Install NPM
    shell: npm install /tmp/angular-project/ --force
  
  - name: Build Project
    shell: ng build 
      

